use_frameworks!

#sources
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/Nang01T2/pods-spec-ios.git'

def shared
  pod 'KeychainAccess'
  pod 'HttpClient', :git => 'https://github.com/Nang01T2/HttpClient.git'
end

target '{{cookiecutter.app_name}}' do
  platform :ios, '12.0'
  
  shared()

  target '{{cookiecutter.app_name}}Tests' do
    #pod 'OHHTTPStubs/Swift'
  end
end
