use_frameworks!

#sources
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/Nang01T2/pods-spec-ios.git'

def shared
  # Utilities
  pod 'SwifterSwift'
  
  # Security
  pod 'KeychainAccess'
  
  # Code quality
  pod 'SwiftLint'
  
  # Logging
  pod 'CocoaLumberjack/Swift'
  
  # Dependency Injection
  pod 'Swinject'
  #pod 'SwinjectStoryboard'
  #pod 'SwinjectAutoregistration'
  
  # Network
  pod 'HttpClient', :git => 'https://github.com/Nang01T2/HttpClient.git'
  
  # Analytics, crash report
end

target '{{cookiecutter.app_name}}' do
  platform :ios, '12.0'
  
  shared()

  target '{{cookiecutter.app_name}}Tests' do
    #pod 'OHHTTPStubs/Swift'
  end
end
